name: ci

env:
  DOCKERHUB_REPO: "xjokay/tor"
  VERSION: "latest"
  MAINTAINER: ${{ github.repository_owner }}
  REPOSITORY: "https://github.com/${{ github.repository }}"
  COMMIT: ${{ github.sha }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          build-args: |
            MAINTAINER=${{ env.MAINTAINER }}
            REPOSITORY=${{ env.REPOSITORY }}
            VERSION=${{ env.VERSION }}
            COMMIT=${{ env.COMMIT }}
            DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}
